language: cpp
compiler: clang

sudo: required
dist: trusty


addons:
  apt:
    packages:
      - libboost-all-dev
      - cmake


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
