language: cpp
compiler:
  - clang++

sudo: required
dist: trusty


addons:
  apt:
    packages:
      - libboost-test-dev
      - clang
      - cmake


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
