language: cpp

sudo: false
dist: trusty


addons:
  apt:
    packages:
      - libboost-test-dev
      - cmake


install:
  - export CXX="clang++"
  - export CC="clang"


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
